### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by kgryte** [math-io/uint32-bits#1]

**Comment by Planeshifter** [comment]
This somehow slipped through. Looks all good. 
Following our discussions, module should be renamed to `uint32-binary-string`. I created a PR with the necessary changes. If you are fine with them, I can update the remaining modules, too.

**Comment by kgryte** [comment]
Should we be consistent with, e.g., `float64-to-words` => `uint32-to-binary-string`? We already do `float64-from-bits` => `float64-from-binary-string`.

**Comment by Planeshifter** [comment]
Hmm, `to-binary-string` and the accompanying function name `toBinaryString` are a bit long, but very explicit. Slightly prefer it to just `binary-string`, though. If you agree, will make the changes for this module and all the other ones.

**Comment by kgryte** [comment]
Re: length, yeah. `math-float64-to-binary-string` is verbose, but explicit. The concern is more about consistency, not just here, but with `float64-to-float32`, `to-array`, `to-matrix`, etc. 

Re: fcn name. In the README, this can be shortened to either `toString` or `bstr` or `tobstr` or `binaryString` or `toBinStr` or `binStr` or `bString`.

**Comment by kgryte** [comment]
So, yeah, let's do `to-binary-string`. And regarding this and the other modules, go for it.

**Comment by kgryte** [comment]
Thanks for updating! Closing this now.
